sudo: false
language: node_js

node_js:
- "5"

cache:
  directories:
    - node_modules

env:
  - MU_APPLICATION_GRAPH=http://mu.semte.ch/application

install:
  - npm install
  - npm install -g codeclimate-test-reporter codecov

script:
  - npm run lint
  - npm run test:cov

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - codecov
