version: "2"
services:

  webcat:
    image: tenforce/webcat:0.2.3
    links:
      - identifier:backend

  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher

  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
    volumes:
      - ./mu/config/dispatcher:/config

  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./mu/data/db:/data

  resource:
    image: semtech/mu-cl-resources:1.10.1
    links:
      - db:database
    volumes:
      - ./mu/config/resources:/config
    environment:
      BOOT: mu-cl-resources

  template:
    image: semtech/mu-javascript-template:latest
    links:
      - db:database
