(in-package :mu-cl-resources)

(add-prefix "dcat" "http://www.w3.org/ns/dcat#")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "dctype" "http://purl.org/dc/dcmitype/")
(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "rdf" "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
(add-prefix "rdfs" "http://www.w3.org/2000/01/rdf-schema#")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "vcard" "http://www.w3.org/2006/vcard/ns#")
(add-prefix "xsd" "http://www.w3.org/2001/XMLSchema#")
(add-prefix "tfdcat" "http://www.tenforce.com/vocabularies/dcat/")
