steps:
  build-release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO/mu-semtech/semtech}
      tags: "${CI_COMMIT_TAG##v}"
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  tag: v*
