steps:
  release:
    image: redpencil/plugin-docker-buildx:latest
    pull: true
    settings:
      repo: ${CI_REPO/mu-semtech/semtech}
      tags: "${CI_COMMIT_TAG##v}"
      platforms: linux/amd64,linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      ssh_key:
        from_secret: ssh_key
when:
  - event: tag
    ref: refs/tags/v*
